### ISSUE TITLE
Changes Color

### ISSUE THREAD

**Issue by javafaiz** [javafaiz/github-crash-course#1]
```css
button {
  color: #0206f9;
  border-radius: 3;
  box-shadow: #bbee03;
  background-color: #f902b7;
  box-sizing: border-box;
}
```
